FROM maven:3.9.9-eclipse-temurin-8 AS builder
WORKDIR /workspace
COPY pom.xml pom.xml
COPY common-lib common-lib
COPY api-gateway api-gateway
RUN mvn -q -pl common-lib,api-gateway -am package -DskipTests

FROM eclipse-temurin:8-jre
WORKDIR /app
LABEL org.opencontainers.image.authors="Anish Kumar"
COPY --from=builder /workspace/api-gateway/target/api-gateway-1.0.0.jar app.jar
ENTRYPOINT ["java","-jar","/app/app.jar"]
