FROM maven:3.9.9-eclipse-temurin-8 AS builder
WORKDIR /workspace
COPY pom.xml pom.xml
COPY common-lib common-lib
COPY notification-service notification-service
RUN mvn -q -pl common-lib,notification-service -am package -DskipTests

FROM eclipse-temurin:8-jre
WORKDIR /app
COPY --from=builder /workspace/notification-service/target/notification-service-1.0.0.jar app.jar
ENTRYPOINT ["java","-jar","/app/app.jar"]
