FROM maven:3.9.9-eclipse-temurin-8 AS builder
WORKDIR /workspace
COPY pom.xml pom.xml
COPY common-lib common-lib
COPY human-review-service human-review-service
RUN mvn -q -pl common-lib,human-review-service -am package -DskipTests

FROM eclipse-temurin:8-jre
WORKDIR /app
LABEL org.opencontainers.image.authors="Anish Kumar"
COPY --from=builder /workspace/human-review-service/target/human-review-service-1.0.0.jar app.jar
ENTRYPOINT ["java","-jar","/app/app.jar"]
